---
- name: "ログディレクトリ"
  file:
    path: "{{ postgresql_logdir }}"
    state: "directory"
    owner: "postgres"
    group: "postgres"
    mode: "0755"

- name: "設定ファイル(postgresql.conf)"
  template:
    src: "postgresql.conf.j2"
    dest: "{{ postgresql_datadir }}/postgresql.conf"
    owner: "postgres"
    group: "postgres"
    mode: "0600"
  notify: "restart_postgresql"